parameters:
    symfony_environment: ~
    database_driver: pdo_mysql
    database_host: ~
    database_port: ~
    database_name: ~
    database_user: ~
    database_password: ~
    database_cert: ~
    database_opts: ~
    database_version: ~

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    locale: en

    # Temp upload folder
    upload_temp_folder: ../tmp/uploads

    # Temp Picture download folder
    user_profile_pictures_path: ../tmp/downloads

    # Authorization Server URL
    oauth_server_url: https://as-uat.esuite.edu/app-mim/oauth/token

    # Authorization Server Assertion
    oauth_server_assertion: client-assertion-mim-readwrite:xnmKFUUiZDAKWol2UuMe4xrt7bqpaMn7a8wtKYSfyU

    # This header contains the Client id
    oauth_header_param: Basic Y2xpZW50LXJzY293bi1taW0tcmVhZHdyaXRlOlBVdDJYMUtubnppT3VuZnJZZHltdnk3S1NxbFJOMDBaZE9sU1IzTUszTQ==

    # Myesuite API Endpoints Provider URL
    myesuite_api_provider_url: https://my-int.esuite.edu/api/rest/mim

    # Embed.ly API Key
    embedly_api_key: 50edb69fb40249fab7466f3616d62981

    # SNS configs for Apple notifications
    aws_access_key_id: ~
    aws_secret_key: ~
    aws_region: ~
    aws_sns_platform_app_arn: ~

    # Course backup related configs
    aws_s3_bucket: ~
    aws_ses_cc_email: ~
    aws_ses_from_email: ~
    aws_ses_review_cc_email: ~
    backup_url: ~
    backup_keypair_id: ~

    # edot Resource Bucket
    edot_resource_bucket: ~
    cdn_bucket: ~

    # Redis server configuration
    redis_host: ~
    redis_port: ~
    redis_prefix: "edot"

    # SSO ADFS logout
    saml_logout: 'https://federation-uat.esuite.edu/adfs/ls/?wa=wsignout1.0'
    adfs_entity_id: ~
    adfs_admin_entity_id: ~
    adfs_ios_entity_id: ~
    adfs_secure_path: '/sso'
    adfs_assertion_consumer_path: '/saml/login_check'
    adfs_logout_path: '/sso/logout'
    adfs_idp_url: 'https://cdn.esuite.edu/adfs/adfs-uat-federationmetadata.xml'
    adfs_cert_file: '/var/www/certs/edot-light-saml-dev.crt'
    adfs_cert_key_file: '/var/www/certs/edot-light-saml-dev.pem'

    # Box OAuth
    box_client_id: ~
    box_client_secret: ~
    box_enterprise_id: ~
    box_master_id: ~
    box_cert_pass: ~
    box_cert_id: ~
    box_base_url: 'https://api.box.com'
    box_upload_url: 'https://upload.box.com'
    box_upload_path: '/api'
    box_api_url: '/2.0'

    # AD Webservice config
    adws_url: ~
    adws_username: ~
    adws_password: ~

    # edot URL
    edot_weburl: ~
    edot_super: ~
    edot_api_id: ~
    edot_api_secret: ~

    # VanillaForums
    vanilla_base_url: ~
    vanilla_api_url: ~
    vanilla_master_token: ~
    vanilla_conversation_limit: ~
    vanilla_category: ~

    sync_myesuite: ~
    aip_enabled: ~
    aip_base_url: ~
    aip_client_id: ~
    aip_client_secret: ~

    barco_weconnect_api_key: ~
    barco_weconnect_api_url: ~

    companion_password: ~
    sso_idp_url: ~
    slo_idp_url: ~
    idp_logout_landing_page: ~

    aip_person_enabled: ~
    aip_person_base_url: ~
    aip_person_client_id: ~
    aip_person_client_secret: ~
    aip_person_keys: ~
