services:
    app.request_listener:
        class: Insead\MIMLoggingBundle\Listener\RequestListener
        arguments:
            $logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9001 }
            - { name: monolog.logger, channel: mim_request_logging }

    app.request_payload_listener:
        class: Insead\MIMLoggingBundle\Listener\RequestPayloadListener
        arguments:
            $logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9000 }
            - { name: monolog.logger, channel: mim_payload_logging }

    app.response_listener:
        class: Insead\MIMLoggingBundle\Listener\ResponseListener
        arguments:
            $logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 501 }
            - { name: monolog.logger, channel: mim_request_logging }

    app.response_payload_listener:
        class: Insead\MIMLoggingBundle\Listener\ResponsePayloadListener
        arguments:
            $logger: "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 500 }
            - { name: monolog.logger, channel: mim_payload_logging }

    mim_standard_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%message%% (%%level_name%%) %%context%% %%extra%%\n"

    mim_request_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%message%%\n"

    mim_payload_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%message%%\n"
