parameters:
#    mim_seed_fixtures.example.class: esuite\MIMSeedFixturesBundle\Example

services:
#    mim_seed_fixtures.example:
#        class: %mim_seed_fixtures.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
