<?php

namespace Insead\MIMBundle\Service\Manager;

use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use Insead\MIMBundle\Entity\Country;
use Insead\MIMBundle\Entity\Programme;
use Insead\MIMBundle\Entity\Course;
use Insead\MIMBundle\Entity\States;
use Insead\MIMBundle\Entity\User;
use Insead\MIMBundle\Entity\UserProfile;
use Insead\MIMBundle\Entity\UserProfileCache;
use Insead\MIMBundle\Entity\UserToken;

use Insead\MIMBundle\Exception\PermissionDeniedException;
use Psr\Log\LoggerInterface;
use Insead\MIMBundle\Service\StudyNotify;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use JMS\Serializer\Serializer;
use Insead\MIMBundle\Service\BoxManager\BoxManager;
use Insead\MIMBundle\Service\StudyCourseBackup as Backup;
use Insead\MIMBundle\Service\S3ObjectManager;

use Insead\MIMBundle\Exception\ResourceNotFoundException;
use Insead\MIMBundle\Exception\InvalidResourceException;

use Symfony\Component\HttpFoundation\Request;

use Insead\MIMBundle\Service\Manager\LoginManager;


class ProfileBookManager extends Base
{
    /** @var S3ObjectManager $s3 */
    protected $s3;
    protected $login;
    protected $secret;
    protected $aip_enabled;

    //https://github.com/chaudhuri-ab/CrossPlatformCiphers/blob/master/PHP_CIPHER/PHP_CIPHER/index.php
    private static $OPENSSL_CIPHER_NAME = "aes-128-cbc"; //Name of OpenSSL Cipher
    private static $CIPHER_KEY_LEN = 16; //128 bits

    private static $BEARER_HEADER  = 'Bearer';

    private static $DEFAULT_AVATAR = '/9j/4Qj+RXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAfAAAAcgEyAAIAAAAUAAAAkYdpAAQAAAABAAAAqAAAANQACvyAAAAnEAAK/IAAACcQQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpADIwMTk6MDk6MTggMTc6Mjc6MzgAAAAAAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAgCgAwAEAAAAAQAAAgAAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABIgEbAAUAAAABAAABKgEoAAMAAAABAAIAAAIBAAQAAAABAAABMgICAAQAAAABAAAHxAAAAAAAAABIAAAAAQAAAEgAAAAB/9j/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwBDQsLDQ4NEA4OEBQODg4UFA4ODg4UEQwMDAwMEREMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIAKAAoAMBIgACEQEDEQH/3QAEAAr/xAE/AAABBQEBAQEBAQAAAAAAAAADAAECBAUGBwgJCgsBAAEFAQEBAQEBAAAAAAAAAAEAAgMEBQYHCAkKCxAAAQQBAwIEAgUHBggFAwwzAQACEQMEIRIxBUFRYRMicYEyBhSRobFCIyQVUsFiMzRygtFDByWSU/Dh8WNzNRaisoMmRJNUZEXCo3Q2F9JV4mXys4TD03Xj80YnlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vY3R1dnd4eXp7fH1+f3EQACAgECBAQDBAUGBwcGBTUBAAIRAyExEgRBUWFxIhMFMoGRFKGxQiPBUtHwMyRi4XKCkkNTFWNzNPElBhaisoMHJjXC0kSTVKMXZEVVNnRl4vKzhMPTdePzRpSkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2JzdHV2d3h5ent8f/2gAMAwEAAhEDEQA/ABpJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKf/0BpJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKf/0RpJJJKUkkkkpSSSSSlJJIWVlU4lJuuJDRo1o+k53ZjP5SSkoBJgalBszMOoxbkVMcOQXif80LHrPW/rBl/YsCl9rnDd9mpMNa39/Judsbt/l3P2f6KtaLvqXjYbjV1X6w9M6fkDR2OHeq5p8LJsxXN/7bSUnrzMO0htWRU9x4AeJ/zSjEEGDoVy/U8KnCzbMWrLo6jWwNIysY7qnbhu28v97Pz/AH2J8PqeXhkNa71KRzS8yP8ArbvpVf2UlPTpIWLlU5dIupMtOhafpNcOWP8A5SKkpSSSSSlJJJJKUkkkkp//0hpJJJKUkkkkpSSSSSlAEmByVzeffd1LqDacYeoS8Y+JX+857hU0/wDX7f8AwNb+VYasS+0csre4fHaYWF9XMfqF/XMCnpfpjPFm/HN8+kHVNdc5120Ods9Nj/oe9JTt/WHqA+r2P/zS6LYazUGu6xns9tt97mh5oY9vupoYxzd+x/7mL/g8j1uTa1rBDAGjwAhGyrr78vIvyTuyLbrH3uEQbC93q7dvt2b/AKCGkpSSSSSm30vMOJltLjFNsMuHaCfZZ/1p3/Q3rpiCDB5C40iQR4iF1uLYbcWi08vrY4/HaJSUlSSSSUpJJJJSkkkklP8A/9MaSSSSlJJJJKUkkkkpHk1G7FvpHNlb2j4kHb/0lg/V7q/7G6xi9W9L7QMfeTSHbC4WVvp0eQ7bt9TeuiBIMjkLmurYZxMs7RFNxL6j2H+kq/627/wNJTTcdz3uiN7nO28xuJftn+TuSSSSUpJJJJSxMAnwXXY1RpxaaTzXWxp+IA3f9Jc90nDOXlguE00kPtPYxrXV/wBcd/4GulJJMnkpKUkkkkpSSSSSlJJJJKf/1BpJJJKUkkkkpSSSSSlIeRj05NLqb27mO100II+i9jvzXtREiNv0vb8dPypKeazOk5eKS4NN9I4tYJIH/C1j3M/89qkHNPBBXZBzQZDmg/1h/eh2VYtpm1lNh8XBjj97klPIlwHJAV3D6Tl5RDi00Unm14gkf8FWfc//AM9roa6sWozUyms+LQxp+9qIXNJkuaT/AFh/ekpHj49ONS2mlu1jdddSSfpPe7857kRIDd9H3fDX8iSSlJJJJKUkkkkpSSSSSn//1RpJJJKUkkkkpSDl5lGHV6txOujGN+k4/us/7+/8xGJa0Fzjta0FzneAGriuUzMt+ZkOvfoDpWz91g+iz/vz/wCWkpNldXzsgkB/oVniuokafy7P5x6pFrSZIk+J1/KnSSUx2M/dH3JbGfuj7lJJJTHYz90fclsZ+6PuUkklLBoBkCD4jT8iu4vV87HIBf69Y5rtJOn8i3+cYqaSSnq8TMozKvVpJ00ex30mn91//fH/AJ6MuUw8t+HkNvZqBpYz95h+kz/vzP5a6sFrgHNO5rgHNd4g6tKSlJJJJKUkkkkp/9YaSSSSlJJJJKaXWbCzpl0fn7a/k5w3f9ELm111tNVzDXcwWVmCWu1EjhB/ZnTf+4tf3H+9JTy6S6j9mdN/7i1/cf70v2Z03/uLX9x/vSU8ukuo/ZnTf+4tf3H+9L9mdN/7i1/cf70lPLpLqP2Z03/uLX9x/vS/ZnTf+4tf3H+9JTy6S6j9mdN/7i1/cf70v2Z03/uLX9x/vSU8uuk6NYX9Mpnlm6v5Ncdv/RKJ+zOm/wDcWv7j/ejVVVU1iulgrrEkNboJPKSmaSSSSlJJJJKf/9caSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSn/9AaSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSn/9n/7RDwUGhvdG9zaG9wIDMuMAA4QklNBCUAAAAAABAAAAAAAAAAAAAAAAAAAAAAOEJJTQQ6AAAAAADlAAAAEAAAAAEAAAAAAAtwcmludE91dHB1dAAAAAUAAAAAUHN0U2Jvb2wBAAAAAEludGVlbnVtAAAAAEludGUAAAAAQ2xybQAAAA9wcmludFNpeHRlZW5CaXRib29sAAAAAAtwcmludGVyTmFtZVRFWFQAAAABAAAAAAAPcHJpbnRQcm9vZlNldHVwT2JqYwAAAAwAUAByAG8AbwBmACAAUwBlAHQAdQBwAAAAAAAKcHJvb2ZTZXR1cAAAAAEAAAAAQmx0bmVudW0AAAAMYnVpbHRpblByb29mAAAACXByb29mQ01ZSwA4QklNBDsAAAAAAi0AAAAQAAAAAQAAAAAAEnByaW50T3V0cHV0T3B0aW9ucwAAABcAAAAAQ3B0bmJvb2wAAAAAAENsYnJib29sAAAAAABSZ3NNYm9vbAAAAAAAQ3JuQ2Jvb2wAAAAAAENudENib29sAAAAAABMYmxzYm9vbAAAAAAATmd0dmJvb2wAAAAAAEVtbERib29sAAAAAABJbnRyYm9vbAAAAAAAQmNrZ09iamMAAAABAAAAAAAAUkdCQwAAAAMAAAAAUmQgIGRvdWJAb+AAAAAAAAAAAABHcm4gZG91YkBv4AAAAAAAAAAAAEJsICBkb3ViQG/gAAAAAAAAAAAAQnJkVFVudEYjUmx0AAAAAAAAAAAAAAAAQmxkIFVudEYjUmx0AAAAAAAAAAAAAAAAUnNsdFVudEYjUHhsQFIAAAAAAAAAAAAKdmVjdG9yRGF0YWJvb2wBAAAAAFBnUHNlbnVtAAAAAFBnUHMAAAAAUGdQQwAAAABMZWZ0VW50RiNSbHQAAAAAAAAAAAAAAABUb3AgVW50RiNSbHQAAAAAAAAAAAAAAABTY2wgVW50RiNQcmNAWQAAAAAAAAAAABBjcm9wV2hlblByaW50aW5nYm9vbAAAAAAOY3JvcFJlY3RCb3R0b21sb25nAAAAAAAAAAxjcm9wUmVjdExlZnRsb25nAAAAAAAAAA1jcm9wUmVjdFJpZ2h0bG9uZwAAAAAAAAALY3JvcFJlY3RUb3Bsb25nAAAAAAA4QklNA+0AAAAAABAASAAAAAEAAgBIAAAAAQACOEJJTQQmAAAAAAAOAAAAAAAAAAAAAD+AAAA4QklNBA0AAAAAAAQAAAAeOEJJTQQZAAAAAAAEAAAAHjhCSU0D8wAAAAAACQAAAAAAAAAAAQA4QklNJxAAAAAAAAoAAQAAAAAAAAACOEJJTQP1AAAAAABIAC9mZgABAGxmZgAGAAAAAAABAC9mZgABAKGZmgAGAAAAAAABADIAAAABAFoAAAAGAAAAAAABADUAAAABAC0AAAAGAAAAAAABOEJJTQP4AAAAAABwAAD/////////////////////////////A+gAAAAA/////////////////////////////wPoAAAAAP////////////////////////////8D6AAAAAD/////////////////////////////A+gAADhCSU0EAAAAAAAAAgAAOEJJTQQCAAAAAAACAAA4QklNBDAAAAAAAAEBADhCSU0ELQAAAAAABgABAAAAAjhCSU0ECAAAAAAAEAAAAAEAAAJAAAACQAAAAAA4QklNBB4AAAAAAAQAAAAAOEJJTQQaAAAAAANJAAAABgAAAAAAAAAAAAACAAAAAgAAAAAKAFMAZQBkAC0AMAAxAC0ANQAxADIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAEAAAAAAABudWxsAAAAAgAAAAZib3VuZHNPYmpjAAAAAQAAAAAAAFJjdDEAAAAEAAAAAFRvcCBsb25nAAAAAAAAAABMZWZ0bG9uZwAAAAAAAAAAQnRvbWxvbmcAAAIAAAAAAFJnaHRsb25nAAACAAAAAAZzbGljZXNWbExzAAAAAU9iamMAAAABAAAAAAAFc2xpY2UAAAASAAAAB3NsaWNlSURsb25nAAAAAAAAAAdncm91cElEbG9uZwAAAAAAAAAGb3JpZ2luZW51bQAAAAxFU2xpY2VPcmlnaW4AAAANYXV0b0dlbmVyYXRlZAAAAABUeXBlZW51bQAAAApFU2xpY2VUeXBlAAAAAEltZyAAAAAGYm91bmRzT2JqYwAAAAEAAAAAAABSY3QxAAAABAAAAABUb3AgbG9uZwAAAAAAAAAATGVmdGxvbmcAAAAAAAAAAEJ0b21sb25nAAACAAAAAABSZ2h0bG9uZwAAAgAAAAADdXJsVEVYVAAAAAEAAAAAAABudWxsVEVYVAAAAAEAAAAAAABNc2dlVEVYVAAAAAEAAAAAAAZhbHRUYWdURVhUAAAAAQAAAAAADmNlbGxUZXh0SXNIVE1MYm9vbAEAAAAIY2VsbFRleHRURVhUAAAAAQAAAAAACWhvcnpBbGlnbmVudW0AAAAPRVNsaWNlSG9yekFsaWduAAAAB2RlZmF1bHQAAAAJdmVydEFsaWduZW51bQAAAA9FU2xpY2VWZXJ0QWxpZ24AAAAHZGVmYXVsdAAAAAtiZ0NvbG9yVHlwZWVudW0AAAARRVNsaWNlQkdDb2xvclR5cGUAAAAATm9uZQAAAAl0b3BPdXRzZXRsb25nAAAAAAAAAApsZWZ0T3V0c2V0bG9uZwAAAAAAAAAMYm90dG9tT3V0c2V0bG9uZwAAAAAAAAALcmlnaHRPdXRzZXRsb25nAAAAAAA4QklNBCgAAAAAAAwAAAACP/AAAAAAAAA4QklNBBQAAAAAAAQAAAACOEJJTQQMAAAAAAfgAAAAAQAAAKAAAACgAAAB4AABLAAAAAfEABgAAf/Y/+0ADEFkb2JlX0NNAAH/7gAOQWRvYmUAZIAAAAAB/9sAhAAMCAgICQgMCQkMEQsKCxEVDwwMDxUYExMVExMYEQwMDAwMDBEMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMAQ0LCw0ODRAODhAUDg4OFBQODg4OFBEMDAwMDBERDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCACgAKADASIAAhEBAxEB/90ABAAK/8QBPwAAAQUBAQEBAQEAAAAAAAAAAwABAgQFBgcICQoLAQABBQEBAQEBAQAAAAAAAAABAAIDBAUGBwgJCgsQAAEEAQMCBAIFBwYIBQMMMwEAAhEDBCESMQVBUWETInGBMgYUkaGxQiMkFVLBYjM0coLRQwclklPw4fFjczUWorKDJkSTVGRFwqN0NhfSVeJl8rOEw9N14/NGJ5SkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2N0dXZ3eHl6e3x9fn9xEAAgIBAgQEAwQFBgcHBgU1AQACEQMhMRIEQVFhcSITBTKBkRShsUIjwVLR8DMkYuFygpJDUxVjczTxJQYWorKDByY1wtJEk1SjF2RFVTZ0ZeLys4TD03Xj80aUpIW0lcTU5PSltcXV5fVWZnaGlqa2xtbm9ic3R1dnd4eXp7fH/9oADAMBAAIRAxEAPwAaSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSn/9AaSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSn/9EaSSSSlJJJJKUkkkkpSSSFlZVOJSbriQ0aNaPpOd2Yz+UkpKASYGpQbMzDqMW5FTHDkF4n/NCx6z1v6wZf2LApfa5w3fZqTDWt/fybnbG7f5dz9n+irWi76l42G41dV+sPTOn5A0djh3quafCybMVzf+20lJ68zDtIbVkVPceAHif80oxBBg6Fcv1PCpws2zFqy6Oo1sDSMrGO6p24btvL/ez8/wB9ifD6nl4ZDWu9Skc0vMj/AK276VX9lJT06SFi5VOXSLqTLToWn6TXDlj/AOUipKUkkkkpSSSSSlJJJJKf/9IaSSSSlJJJJKUkkkkpQBJgclc3n33dS6g2nGHqEvGPiV/vOe4VNP8A1+3/AMDW/lWGrEvtHLK3uHx2mFhfVzH6hf1zAp6X6YzxZvxzfPpB1TXXOddtDnbPTY/6HvSU7f1h6gPq9j/80ui2Gs1BrusZ7Pbbfe5oeaGPb7qaGMc3fsf+5i/4PI9bk2tawQwBo8AIRsq6+/LyL8k7si26x97hEGwvd6u3b7dm/wCghpKUkkkkpt9LzDiZbS4xTbDLh2gn2Wf9ad/0N66YggweQuNIkEeIhdbi2G3FotPL62OPx2iUlJUkkklKSSSSUpJJJJT/AP/TGkkkkpSSSSSlJJJJKR5NRuxb6RzZW9o+JB2/9JYP1e6v+xusYvVvS+0DH3k0h2wuFlb6dHkO27fU3rogSDI5C5rq2GcTLO0RTcS+o9h/pKv+tu/8DSU03Hc97oje5ztvMbiX7Z/k7kkkklKSSSSUsTAJ8F12NUacWmk811safiAN3/SXPdJwzl5YLhNNJD7T2Ma11f8AXHf+BrpSSTJ5KSlJJJJKUkkkkpSSSSSn/9QaSSSSlJJJJKUkkkkpSHkY9OTS6m9u5jtdNCCPovY7817URIjb9L2/HT8qSnmszpOXikuDTfSOLWCSB/wtY9zP/PapBzTwQV2Qc0GQ5oP9Yf3odlWLaZtZTYfFwY4/e5JTyJcByQFdw+k5eUQ4tNFJ5teIJH/BVn3P/wDPa6GurFqM1MprPi0MafvaiFzSZLmk/wBYf3pKR4+PTjUtppbtY3XXUkn6T3u/Oe5ESA3fR93w1/IkkpSSSSSlJJJJKUkkkkp//9UaSSSSlJJJJKUg5eZRh1ercTroxjfpOP7rP+/v/MRiWtBc47WtBc53gBq4rlMzLfmZDr36A6Vs/dYPos/78/8AlpKTZXV87IJAf6FZ4rqJGn8uz+ceqRa0mSJPidfyp0klMdjP3R9yWxn7o+5SSSUx2M/dH3JbGfuj7lJJJSwaAZAg+I0/IruL1fOxyAX+vWOa7STp/It/nGKmkkp6vEzKMyr1aSdNHsd9Jp/df/3x/wCejLlMPLfh5Db2agaWM/eYfpM/78z+WurBa4BzTua4BzXeIOrSkpSSSSSlJJJJKf/WGkkkkpSSSSSml1mws6ZdH5+2v5OcN3/RC5tddbTVcw13MFlZglrtRI4Qf2Z03/uLX9x/vSU8ukuo/ZnTf+4tf3H+9L9mdN/7i1/cf70lPLpLqP2Z03/uLX9x/vS/ZnTf+4tf3H+9JTy6S6j9mdN/7i1/cf70v2Z03/uLX9x/vSU8ukuo/ZnTf+4tf3H+9L9mdN/7i1/cf70lPLrpOjWF/TKZ5Zur+TXHb/0Sifszpv8A3Fr+4/3o1VVVNYrpYK6xJDW6CTykpmkkkkpSSSSSn//XGkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkp//QGkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkpSSSSSlJJJJKUkkkkp//ZOEJJTQQhAAAAAABTAAAAAQEAAAAPAEEAZABvAGIAZQAgAFAAaABvAHQAbwBzAGgAbwBwAAAAEgBBAGQAbwBiAGUAIABQAGgAbwB0AG8AcwBoAG8AcAAgAEMAQwAAAAEAOEJJTQQGAAAAAAAHAAgBAQABAQD/4Q5OaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLwA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/PiA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA1LjYtYzE0MCA3OS4xNjA0NTEsIDIwMTcvMDUvMDYtMDE6MDg6MjEgICAgICAgICI+IDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+IDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDQyAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMTktMDktMThUMTc6MjU6MDIrMDg6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDE5LTA5LTE4VDE3OjI3OjM4KzA4OjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDE5LTA5LTE4VDE3OjI3OjM4KzA4OjAwIiBkYzpmb3JtYXQ9ImltYWdlL2pwZWciIHBob3Rvc2hvcDpDb2xvck1vZGU9IjMiIHBob3Rvc2hvcDpJQ0NQcm9maWxlPSJzUkdCIElFQzYxOTY2LTIuMSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDoyY2UxN2E3NC01ZGRlLTRmN2EtOGUyNC04MjhkNjE4YjE3MDEiIHhtcE1NOkRvY3VtZW50SUQ9ImFkb2JlOmRvY2lkOnBob3Rvc2hvcDo3MTM3NGM2Yy01OTMzLTFiNGMtYmFmNy1jZjUwMDQxN2QxMTAiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDpiMTQ4Y2Q2NS1jYWIzLTQ1NDUtYjllZi04YzYwMzlmZWI5NWYiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmIxNDhjZDY1LWNhYjMtNDU0NS1iOWVmLThjNjAzOWZlYjk1ZiIgc3RFdnQ6d2hlbj0iMjAxOS0wOS0xOFQxNzoyNTowMiswODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjb252ZXJ0ZWQiIHN0RXZ0OnBhcmFtZXRlcnM9ImZyb20gaW1hZ2UvcG5nIHRvIGltYWdlL2pwZWciLz4gPHJkZjpsaSBzdEV2dDphY3Rpb249InNhdmVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjJjZTE3YTc0LTVkZGUtNGY3YS04ZTI0LTgyOGQ2MThiMTcwMSIgc3RFdnQ6d2hlbj0iMjAxOS0wOS0xOFQxNzoyNzozOCswODowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIiBzdEV2dDpjaGFuZ2VkPSIvIi8+IDwvcmRmOlNlcT4gPC94bXBNTTpIaXN0b3J5PiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8P3hwYWNrZXQgZW5kPSJ3Ij8+/+IMWElDQ19QUk9GSUxFAAEBAAAMSExpbm8CEAAAbW50clJHQiBYWVogB84AAgAJAAYAMQAAYWNzcE1TRlQAAAAASUVDIHNSR0IAAAAAAAAAAAAAAAEAAPbWAAEAAAAA0y1IUCAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARY3BydAAAAVAAAAAzZGVzYwAAAYQAAABsd3RwdAAAAfAAAAAUYmtwdAAAAgQAAAAUclhZWgAAAhgAAAAUZ1hZWgAAAiwAAAAUYlhZWgAAAkAAAAAUZG1uZAAAAlQAAABwZG1kZAAAAsQAAACIdnVlZAAAA0wAAACGdmlldwAAA9QAAAAkbHVtaQAAA/gAAAAUbWVhcwAABAwAAAAkdGVjaAAABDAAAAAMclRSQwAABDwAAAgMZ1RSQwAABDwAAAgMYlRSQwAABDwAAAgMdGV4dAAAAABDb3B5cmlnaHQgKGMpIDE5OTggSGV3bGV0dC1QYWNrYXJkIENvbXBhbnkAAGRlc2MAAAAAAAAAEnNSR0IgSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAADzUQABAAAAARbMWFlaIAAAAAAAAAAAAAAAAAAAAABYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9kZXNjAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAABZJRUMgaHR0cDovL3d3dy5pZWMuY2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAuSUVDIDYxOTY2LTIuMSBEZWZhdWx0IFJHQiBjb2xvdXIgc3BhY2UgLSBzUkdCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRlc2MAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAACxSZWZlcmVuY2UgVmlld2luZyBDb25kaXRpb24gaW4gSUVDNjE5NjYtMi4xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2aWV3AAAAAAATpP4AFF8uABDPFAAD7cwABBMLAANcngAAAAFYWVogAAAAAABMCVYAUAAAAFcf521lYXMAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAKPAAAAAnNpZyAAAAAAQ1JUIGN1cnYAAAAAAAAEAAAAAAUACgAPABQAGQAeACMAKAAtADIANwA7AEAARQBKAE8AVABZAF4AYwBoAG0AcgB3AHwAgQCGAIsAkACVAJoAnwCkAKkArgCyALcAvADBAMYAywDQANUA2wDgAOUA6wDwAPYA+wEBAQcBDQETARkBHwElASsBMgE4AT4BRQFMAVIBWQFgAWcBbgF1AXwBgwGLAZIBmgGhAakBsQG5AcEByQHRAdkB4QHpAfIB+gIDAgwCFAIdAiYCLwI4AkECSwJUAl0CZwJxAnoChAKOApgCogKsArYCwQLLAtUC4ALrAvUDAAMLAxYDIQMtAzgDQwNPA1oDZgNyA34DigOWA6IDrgO6A8cD0wPgA+wD+QQGBBMEIAQtBDsESARVBGMEcQR+BIwEmgSoBLYExATTBOEE8AT+BQ0FHAUrBToFSQVYBWcFdwWGBZYFpgW1BcUF1QXlBfYGBgYWBicGNwZIBlkGagZ7BowGnQavBsAG0QbjBvUHBwcZBysHPQdPB2EHdAeGB5kHrAe/B9IH5Qf4CAsIHwgyCEYIWghuCIIIlgiqCL4I0gjnCPsJEAklCToJTwlkCXkJjwmkCboJzwnlCfsKEQonCj0KVApqCoEKmAquCsUK3ArzCwsLIgs5C1ELaQuAC5gLsAvIC+EL+QwSDCoMQwxcDHUMjgynDMAM2QzzDQ0NJg1ADVoNdA2ODakNww3eDfgOEw4uDkkOZA5/DpsOtg7SDu4PCQ8lD0EPXg96D5YPsw/PD+wQCRAmEEMQYRB+EJsQuRDXEPURExExEU8RbRGMEaoRyRHoEgcSJhJFEmQShBKjEsMS4xMDEyMTQxNjE4MTpBPFE+UUBhQnFEkUahSLFK0UzhTwFRIVNBVWFXgVmxW9FeAWAxYmFkkWbBaPFrIW1hb6Fx0XQRdlF4kXrhfSF/cYGxhAGGUYihivGNUY+hkgGUUZaxmRGbcZ3RoEGioaURp3Gp4axRrsGxQbOxtjG4obshvaHAIcKhxSHHscoxzMHPUdHh1HHXAdmR3DHeweFh5AHmoelB6+HukfEx8+H2kflB+/H+ogFSBBIGwgmCDEIPAhHCFIIXUhoSHOIfsiJyJVIoIiryLdIwojOCNmI5QjwiPwJB8kTSR8JKsk2iUJJTglaCWXJccl9yYnJlcmhya3JugnGCdJJ3onqyfcKA0oPyhxKKIo1CkGKTgpaymdKdAqAio1KmgqmyrPKwIrNitpK50r0SwFLDksbiyiLNctDC1BLXYtqy3hLhYuTC6CLrcu7i8kL1ovkS/HL/4wNTBsMKQw2zESMUoxgjG6MfIyKjJjMpsy1DMNM0YzfzO4M/E0KzRlNJ402DUTNU01hzXCNf02NzZyNq426TckN2A3nDfXOBQ4UDiMOMg5BTlCOX85vDn5OjY6dDqyOu87LTtrO6o76DwnPGU8pDzjPSI9YT2hPeA+ID5gPqA+4D8hP2E/oj/iQCNAZECmQOdBKUFqQaxB7kIwQnJCtUL3QzpDfUPARANER0SKRM5FEkVVRZpF3kYiRmdGq0bwRzVHe0fASAVIS0iRSNdJHUljSalJ8Eo3Sn1KxEsMS1NLmkviTCpMcky6TQJNSk2TTdxOJU5uTrdPAE9JT5NP3VAnUHFQu1EGUVBRm1HmUjFSfFLHUxNTX1OqU/ZUQlSPVNtVKFV1VcJWD1ZcVqlW91dEV5JX4FgvWH1Yy1kaWWlZuFoHWlZaplr1W0VblVvlXDVchlzWXSddeF3JXhpebF69Xw9fYV+zYAVgV2CqYPxhT2GiYfViSWKcYvBjQ2OXY+tkQGSUZOllPWWSZedmPWaSZuhnPWeTZ+loP2iWaOxpQ2maafFqSGqfavdrT2una/9sV2yvbQhtYG25bhJua27Ebx5veG/RcCtwhnDgcTpxlXHwcktypnMBc11zuHQUdHB0zHUodYV14XY+dpt2+HdWd7N4EXhueMx5KnmJeed6RnqlewR7Y3vCfCF8gXzhfUF9oX4BfmJ+wn8jf4R/5YBHgKiBCoFrgc2CMIKSgvSDV4O6hB2EgITjhUeFq4YOhnKG14c7h5+IBIhpiM6JM4mZif6KZIrKizCLlov8jGOMyo0xjZiN/45mjs6PNo+ekAaQbpDWkT+RqJIRknqS45NNk7aUIJSKlPSVX5XJljSWn5cKl3WX4JhMmLiZJJmQmfyaaJrVm0Kbr5wcnImc951kndKeQJ6unx2fi5/6oGmg2KFHobaiJqKWowajdqPmpFakx6U4pammGqaLpv2nbqfgqFKoxKk3qamqHKqPqwKrdavprFys0K1ErbiuLa6hrxavi7AAsHWw6rFgsdayS7LCszizrrQltJy1E7WKtgG2ebbwt2i34LhZuNG5SrnCuju6tbsuu6e8IbybvRW9j74KvoS+/796v/XAcMDswWfB48JfwtvDWMPUxFHEzsVLxcjGRsbDx0HHv8g9yLzJOsm5yjjKt8s2y7bMNcy1zTXNtc42zrbPN8+40DnQutE80b7SP9LB00TTxtRJ1MvVTtXR1lXW2Ndc1+DYZNjo2WzZ8dp22vvbgNwF3IrdEN2W3hzeot8p36/gNuC94UThzOJT4tvjY+Pr5HPk/OWE5g3mlucf56noMui86Ubp0Opb6uXrcOv77IbtEe2c7ijutO9A78zwWPDl8XLx//KM8xnzp/Q09ML1UPXe9m32+/eK+Bn4qPk4+cf6V/rn+3f8B/yY/Sn9uv5L/tz/bf///+4AIUFkb2JlAGRAAAAAAQMAEAMCAwYAAAAAAAAAAAAAAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAgICAgICAgICAgMDAwMDAwMDAwMBAQEBAQEBAQEBAQICAQICAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA//CABEIAgACAAMBEQACEQEDEQH/xACsAAEAAgICAwEBAAAAAAAAAAAACAkHCgUGAgMLBAEBAQAAAAAAAAAAAAAAAAAAAAAQAAECBQQCAgICAwEAAAAAAAcFBgADBAgYUAECCUAKEDAgEpDAcBEXExEAAQQBAgMEBggDBgYDAAAAAwECBAUGEQcAEhMhFNU2QFAikhUIEDAxQWEyFpYgUVKQcUJyIyRwgZGCJReiNAkSAQAAAAAAAAAAAAAAAAAAAMD/2gAMAwEBAhEDEQAAAOngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/OR3MFmPgZBM6kiD3gAAAAAAAAAAAAAAAAAAAAAAAAAA4Ur1ICHTgAAdyJ9lhRzIAAAAAAAAAAAAAAAAAAAAAAAABgIp1MbAyKWYGWiHJXsADJRcWZ7AAAAAAAAAAAAAAAAAAAAAAAAIyFLxxZJQ3Xy+0rGMJHZD50IABypdESZAAAAAAAAAAAAAAAAAAAAAAAMXFEJ14sgPpDmqiaoB0UAAAA7EXvmTwAAAAAAAAAAAAAAAAAAAAADzKQyNBl0+pwaFhR6AAAAACTRdyeAAAAAAAAAAAAAAAAAAAAAAI1FIgN0I78aP4AAAAAALviSQAAAAAAAAAAAAAAAAAAAAAKjyD4PrGnzLyIQAAAAAAJxltoAAAAAAAAAAAAAAAAAAAAB5mvUdBBsMGvOAAAAAAAZANhM8AAAAAAAAAAAAAAAAAAAAAcKa5IMsGwaazQAAAAAAANjk5cAAAAAAAAAAAAAAAAAAAAHRTXpBaibtZ80MAAAAAAAGwqd7AAAAAAAAAAAAAAAAAAAABwBrnAtKN3Y+Z+AAAAAAADYzOdAAAAAAAAAAAAAAAAAAAAB7DXgOlHNFjRWWAAAAAAAd4Nhw9YAAAAAAAAAAAAAAAAAAAABUIQqAAAAAAAABNgt4AAAAAAAAAAAAAAAAAAAAABFkpVAAAAAAAABdYSkAAAAAAAAAAAAAAAAAAAAAB/SjAj6AAAAAAACQpeaeIAAAAAAAAAAAAAAAAAAAAABhwonOKAAAAAAByxeyZhAAAAAAAAAAAAAAAAAAAAAAAImFNp+QAAAAAH6y5QliAAAAAAAAAAAAAAAAAAAAAAAARnKeDpwAAAAO5Fw5JcAAAAAAAAAAAAAAAAAAAAAAAAA6qVukFDhgAAcyTtLITtIAAAAAAAAAAAAAAAAAAAAAAAAAAOJIvGAzqQO2mfSUBywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABj8icYTMdnGAAAAAAA5MyIZtJYGQAAAAAAAAAAAAAAAAAAAAYoKwiIh/AAAAAAAAAAf0l4WemVgAAAAAAAAAAAAAAAAACEJU8ccAAAAAAAAAAADki2Im4AAAAAAAAAAAAAAAAAQJKpQAAAAAAAAAAAAAWuE9AAAAAAAAAAAAAAAACOZSCekAAAAAAAAAAAAAHvLvyRQAAAAAAAAAAAAAAB6ihQw+AAAAAAAAAAAAAADMJfUe0AAAAAAAAAAAAAAERimgAAAAAAAAAAAAAAAFzJLcAAAAAAAAAAAAAAFPxDAAAAAAAAAAAAAAAAE0i34AAAAAAAAAAAAAAGvmY7AAAAAAAAAAAAAAABkc2CQAAAAAAAAAAAAAD95rQAAAAAAAAAAAAAAAAA2Xz8AAAAAAAAAAAAAAPYVaHDAAAAAAAAAAAAAAAA5ktLPWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//2gAIAQIAAQUA/oAH/9oACAEDAAEFAP6AB//aAAgBAQABBQD+dytq6NNoHfdqBWfyWOwdn0igq9gjmnTErsEcsmYj9g7Pq1BoXaAZ470VXSKVBqzicbfaCKVr8v05PMgvciKP5MshvgdKApvy4zOTecaA7kXUzpcI0Agkk4tPkvL3wNRAWTMuMDog7XiLTVfrjdslNTHnqk7ErZ2z+AwLb6EK6DLg2eb0nUbkbiU8KIS2tq7kVotYtDuGvRJ9ifrG20BqjXnnaFY0NSZ7GvVYPKqk9pHrXqaox+xv1dTwN+KGuLDaV7brh042IOnmIqogcYrsdbgfDjjrO61TH2UHEBW72ldZdtnZB7OT3cyiRygSDE7fpabrcDGcgfKiIYmJpsuXzmzLpzLyLhIgCA8iXKGaze1AE9Z9pXcn3APzsSJ/2WrGXcSEiZL5ypmmXYErYcBz49Veyqj5UvtDdgigzGl91qJK/wCkBzTL8HrPWip8daIGo7XrBL+bkFG7i8n7rDXtORijpcuXznTCo6KZ7Ev4qfZHvaqrQvvFDopmUTpkvnK56U5HFu0G58AgOO24c1dlnrtKli1p3gN9xbO9B0op7cdxP8dI6NKXu1X2KVuak9SngCr9f+TaU7G/OdzV+Ok9zULT7UfYkbc5f6lvAa7e5tFs6VJnTKecSWxIZRDhtuNfZziuy7fL9L1xJ94ybFO9SNOmzJ83S76mZOQy94VibLnrhb0y8Eb7v8OeFaAN9x+G9M48v15XKB6YHST4FtAc5mIk8uW/Plpp0D6WamEuoas2ln7kFCV3OtAwQJYVYWn3O22UhkTa+gr0qv8AsT0+vVq+2O2ujDSbqJ/tmbBtlPpgPAar/wBTFHzxJa8AbZ2uEpOpvJjtAhohSsPciXzX244Wop/kgNxwutSFlh7iU+bNZDRHqJqy6gIDpT3PZKCV7kude1fIoduvkr78d+vkr/qh9e1dPoWxZMCEDkhoCC16D/GL4K40GvJy3+jtOmVvYETOU1SvTPVdNzEuEjMS4SMxLhIzEuEjMS4SMxLhIzEuEjMS4SMxLhIzEuEjMS4SMxLhIzEuEjMS4SE29M9UM2i7AiZxmtq/0dKUxjlYakrfSCqax4G08o3nFZ98999+W/ibb78dxdeeVmLzFhqHZjT9FuOu5ohxUK6wrOBT8hIWFdvqduF3FESanQ7s7neTM28y0257k9OOg3LnCUFmJUVFRV1HmUtVU0VTbSb5ZpYnn1FRS0dOdSrWmIk+cCCrVh0kyKilq5HnXpEWYyRBoFl5F5vcP+dfS7Jy0ZtAsUdk1GMnm7bf7gur9G6iroAeXqRrljzUqZwlKmhK3LhzVPMlc9pU1f6/3TLVsAiTGARJjAIkxgESYwCJMYBEmMAiTGARJjAIkxgESYwCJMYBEmMAiTGARJjAIkxgESYwCJMYBEmMAiTGARJjAIkxgESYwCJMYBEmMAiTGARJjAIkxgESYwCJMYBEmMAiTGARJhv9f7omK06Z/wC07+c7/9oACAECAgY/AAAH/9oACAEDAgY/AAAH/9oACAEBAQY/AP7dyXa2cyHWVNexhLG2s5ceuqq4RHoNhrCymEBCggV66c5SMYn8+JICZk7KbCFMHFk1eEVsm/M9j0G50uBdnWswuyjjYTVVDbOVVarfzJpwUdBthkl/VdNOhMuMpq8QsELq7mQtbCpM3jKNE00VJaKvb2cKtJtxRV4tOxlre2FyRF/EsSFRNVP+xOEW823orEXZqyqvZ9MRf56Elwb1qe4vAh3+2GS4/VdJ3XmU+UVeX2Cm1byoKtm0mDxkEqa6qstVTs7F4igHma4tYzZhIsaqziukY+Zg2IRzZc+7EtlhVbHIweqKW2RdXI3TmXTiHa1suJZVViNxq61rZQJ9XYga9RrIr7GGQ0KdH50VEIJ72L9y+t5mR5VdV2PUNen+7tbSQkeKwihPIHFCiI886xkiikUESOwsqS5itCN79G8S6fZyjaunXj/rfK4qEdze0NsvHsV53AZ0jDQoD2jztMEnIeuE9F4baZvlN1kssT5ToiWk0polYybIWVJjU1cisrqWA87uZI8QQQN7EaxERE/jdaYRlNzjUor4rpjayYQUKzZCP3mNGuax6vrbuCI/td3liMByqurF1XiJTbx0bGa9CP8ArjFI3KvN/pidLyLFlJ0ndQpHGkSKt4WhExGAriOXiFkeLXNdkFDYNRYlrVyGyIpH9EEgkYvY00KwjClD68U7BSoznIww2P1anrPkm6Xua2IEfQ4fEkNEdwyaolxfSUaVaeiFp7Cq10iaXQYGKxJEiM6+zW4JMURJHwmmjc8agx2LI6KOg0VX1CDhhUUYTSFcpJUpRNJJKY3MRfobjG0G2G4W6mSOUelBtzhmR5tc/wCqqtGq1mNVtnMa16tXRVYidi/y4ZOqflEymhhvY16lz/NNr9u5LEfpyo+nzTN6S+5+3takVVb9+nDTh2Jw6eVzdVhxN79oWSWLr+Vzp2YQoiu/ylVPx4vc13m+VDc3G8NxiMSdkmX0wqLcDFqCuCuhrS6yHbq6yyoq6oGqdSUczI7NU5npqn8Lb3C7d8TrEjrb0stHysfyKNGUyMhXlX1BjliQUkrRmY4UuKpXPjmCXQiOSB/4LM60PPfYfMkMLJGJvKnxmik8ovjNCZXIj3IxkiEbUZxox0c8n1iytp0jWW4t9EISirztYeJSQnPJHXJbiO7VpxsMN7IcZ3sSTjcpNRCewlhfX1jLt7m1lFm2NlPM+RLmSjO5iFMV6q5yr9iJ9jWoiIiIiJ9ELaT5cdtrncLLDMHLtTRUFBxvEqZxUEXIczyee+PS4zSBdqiFkmY45dAgYY7xifR5t85F6T5k9zRjBMk4FUybTG9jcfnpoTu3dwLW5fuE6GZqaHnmgV8liq0tYqdq10K/yHYH5VNq4CEHSVEiZgu0WKvMITEJGoaUbqSJY2TxtanSiBLIKuicrlVOJEGr3kzPdOZEK4Mge2e1ObS4qEYuju73GYVuGUdgL+RY0ownfc5eFjmxv5oK8SPRiTpe1+GPiq1VTUqMgbpzZvI3Xt1CjuzsReNxbDGM4ync3M7HD7+pp9j7HaPcSom5bPt6mVAj015e3mNAwGBj0oslB2BX2hXsiKRRBO/lE/8Ahr76gsZdRc1UkcyusoJnAlRJIl9kgiMXXtRVa5q6te1Va5FaqopK+2SLW7iUEQZL6tAjQxbmEjxx0yWnAi6BAQ5GMlx2+zGkEbyaCKNjPV9nmVug5ctitrscpHdVX32RyxHfX17+g8RA1wmgfImGUgunFC9BudIcARLjLcpsj29/ezHzbGcfkbzkVrRhBHAJrI8KBCjDYCNGC1gI0cbBCYwbGtTgW3WC9bFNtcW7la7xbvzK4k2jwHHZBSJHixgqSMK6zTIljkFVVjSsedzCGI4cUEgw5WNYJFxXZ7aHb+mdke4u5GX2FbBssglwo7R2WdbmZnKZCW4u5jl5WufyBAjmRYYQgaGO2/2o/wDzzgphOJRzSK2X8x2XUkeZmeSjbzANI25wi+hnrcPqT6OUM+3BKtDCe17YtcZmq2mfbsZ7mG5WbXRXGtcsznI7bKcgnOV73o2Ra3UuZMcIavXkHzowadjUROz6qny3FbI9Rf0Uts2unA5Hcj0a8RgSAFaSPNgToxHgkxjNeCTHI8RWPG9zVq8zp0ZFklV9fkNKnU6lBkcQYX2NailcRx4L2nHIhmR5OrEOPqK06GEL1awQmOIQj2jGNjVc973qjWMY1NVc5zl0RE7VXiSyqmrIwfDnSqLEGiIdYk5OoNLrKGDKrG9TJZsZrhP6IC/DgRBFb1BK5eNt9h9p6Z17uFullVbieNwNSMjDkziK6Va2kgYzLBoqKuEadYSVarIsKOUzvZYvFTtXjVlU0eIbd4/Z51u9unkHc6VcqySPVNsM83Ny+cUqigxGxq5ekwpiDraqKCMhHMAjlnYBt5Z3WJfKHgN0UeB4YhJFdI3Js68xQj3R3Ahoo3yZ85NXVNcdFHTxHJ7PeySSv+sjBtpvd8HzN0Siy1CkM2JXr1SJR5QRjHKxH43OlOcYiiMRK6RLGJnUK1UeIrHDKN7hkG9qseN7FVr2Pa5Ec1zXJoqL2ovq29bCkMHkWaquF0g0JFWQGPbRpC5FbJFP/rkjQqARo6HBoSJPmxCIqfTu98+OY1rSzUlzti9l0lg/+oIcequt0cuhoZqtUkvvVfTRJQtHMaO0AqqhHImHfIFtnd91tNx6yFuP8wEyvkq2XGwaNZqmA7flIFXdJuVXdWa0sQuUZkiV8Jqo+PNI1311Cs2QwmRYYqYXeNcSKkiQOojRloLbuwXOktjzqA0cL5B/9SXYRJb9V7fVtThDCSmQMAx2Ipohu7OjfqHMI8TIZ1jBIFFL0pmNvpwvYR2rDRX6Imq6/R8q+z74QKixxrZvF73Mw6NCwOd5tDXPdwiGK7lV6Dy/I5ydR+i9NqaoiJonzFfMLNmPmQtxNzb+Tiivc9yxNvqMrMZ25rUV/wBq1mC01eByojUe8au5W82ifXXODEJKdBz/AB6SSPEA2OgVyHDgzL+FOmlLoVkeHjPxkbWsdq80hmqLomnqsYhMcQhXtGNjU1c973I1jGonarnOXROM/wAtgvkvrcizDIrapbMIUkgFLLtZRaaG5TOcRrINWoQsYq+wwaNTRERPpf8ALC7Fts25abbxdqz/ADBMDfpnhMTdSrjpLRtL8T/Tws/JTryLbI3ooZVO2I02j0+v2/yyeWSGsx/Mcds7lYbzDkFo41pGdeRWqBUK5k2p6wXsT87Hq3RUXTh4iMcMg3uGRj0VrmPYqtcxzV7Uc1yaKn8/VeQZc1ivXFaO3yXkaiqqtoa+RbO7ERV0RsRdfw+nanYnBO4pmO724GKbeY6azMSPVw7PK7mJTx7C1OIRzAq65ZSnkvYMj2gG5Wtc5Eatp8z2B/MOTd4G25MWFu3jN5gYMMIyBk99VYoPJcLlRMnyBxwQMku4jC10pql7oV50kqoVCT0Cjy1qcrcpp6zJGJoqexewQWjNEXRdFbKTT8PVe7nMuif+pd0V/wC5MCyFWp/zdp9PyXwSsR7Abm2VyjVTXQuOYLluQhf/AHjNVtcn4px8x0QT1YuQ32x9I9Wro5RJvht9dEYioqLoRtNyu/m1VT7F9B2k5Ps/9TbYa/5lwTH1f/8APX1Xk+Jge4Zsqxy9xkb2ro5q39VLqexdF01SZ9PyXWlgZgASt1JGMjeRUa107NMOyjDqwKKvZzyLK+ENqfarnInHzHSgPG12L3Wy2SPaQjR9UI96cCpzMY5yo1SNFcq9G66u5NE1cqIvoGOYkRyufi1BTY2qqquX/wADWxqpE1d2qiJE07fVYjheozAIwwnppqwg3I9j01RU1a5qLxnWIRDEkw8Xy/I6CDKKitfMgVNvMgwZi6tbzNmRAsK12mjmvRU7F+ihy7Fbixx3KMWuqvI8byCnlmgW1HfUk4FnT3FXOjvZIhWNZYRRmAVjkeMrGuaqKicUmx+/m70W626rZdXZ3FNjmH4vhr84uKVUJU2ebyccrYJLl1fJRJA4rOhX96aw6x1MIJB/X4HiEx5hQcmzDHKOxkR2ucWLW2dvEiWUxORrla2FBKQrnaaMaxXL2IvBTmepCmI8pSO/M8hHK9710+9zlVfVkXLxsO6vz7HayWp+6tjwg3eMxgYzY1cV7URJBg1MCumyHLqvUsO1e3RPQp2YvZIZX4BjlidklscR4Rb3KY8jGq+rmKRHKF8ikmWksD2oioWAnanZr6stLKDGYa+27KbMq56CY+S+ljxlHmUARzyo4YcR1KxtkdUQhDOqAiY1XOT0OqsZsYYr7cMgc0sSdITZLKWXFYzDq8skEqQKbEZSOWyDqgyAJbGE5qOavq1rkRjla5HIj2MIxdF10eMjXDIxfva5FRU7FTTixrYEYzMNyBS3uFSXc5BMqZJl69E6Q+VNKSbjMtyxHqYiSDAaGU9jGyRovoECvsIxn4ZjvSvs1kN6oxFrAGRItA2SKVCKObk0xqRW9EveQxlPKGx6Rnpw566aucrl5WtY3Vy6rysYjWMTVexERET7vV0zF5L4kG+hOJaYdeygue2nvmC5EDJMBj5o6S7ExI05okKiN6cjonLFAzi0x69gmrLmlnSa2zgSEb1ok2IVwThcrHPG9GvaujmOcx7dHNVWqir9dV47QQDWd1dTo1bWQI/J1ZUyWRogia4jmCG1Xu1c97mjY1Fc5yNRVSFi0V8OdeTHMtMvvYoHsS4viCRjhxzSWMmkpKYSrGgtI0SKxHyFAE0k7V9X/qnFhRYG6FPDYABCEDDhZrWRWcseiupBXDjxriGNOStsSOa1rESJLd3ZI5oE2rtIUuts62XJgWNdPjGhz4E+GZ8eXCmxJDByIsuLIG4ZBka17HtVrkRUVPrYVVVQpdnZ2cuNX11dXxjTJ9hPmGZGhwoUOMwkiXLlyCNGMY2ueR7ka1FVUTj9UZQOLYboXENwJJRkDLg4VWSmaSKGlkBcSPLt5g15LKxG5zHN1iRHd27wew9YrdQzxsX3FjQ2RIuSqEi112GKFBV0DMI8QRZUkMQY2gDPCwk2LF0YrJQgx44zY1m1HLorYYkkiFI6ZY06E8pgDsKufGeaDa1xTxyDaeOQglIN7ObnY5qfVCxvCaKZe2rxLJMOP0wxYEJpRAfYWtjJIGBVV7DyBjU8ggx9UjGIqvexqtuZZouUbiyYb40vJ+g9IFKOUBwbGvw4EsIpUQEoRXxyzysHNlxVczkiiOeM/wBZvx3Nser8kp3PUwo09pmGgyVcFyzKqxiFjWdPNekdjHmimCQgkUT1cJz2OPZ7R3LcrruZXJjGRyq+pyeKzV3sxbknw/Gr1gQiUhHk+Fm5ntEGOd3tKalyiiucbuYzBEkVN9WTaiyAM42mA8sGwBHkjYcL0exVaiOaqKmqL/GKlxehuckuDjMUNVQVc64sjCjjcU5BQa8EiUQYBNVz3I1Ua1FVdE4BZ7uXLcWr+bmXFsblV9tk8piKnZLux/EMaohlERpBvF8VKqtcIwAO0cjMcwnH6/G6ZpFOSLAaZ5ZknnM5JdpYSzSbO3msQ7mMNLMYow8omOaJjGN9bMqcooaTJqsRiyQ1uRVFfeQI8s0d0V82NDtI0qPGn93erWnG1pmJ+VycKarr8nwso4TgBDjWRlk15pirq2fYx8ui5TNOqL2KKNJhjVPsRPtTqY1urDtLNW6pCvsPPQV7Xr/hW0rsjyWS5jf6khoq/wBPCO/Xu0aKqfkWz3A5k/BVTbhWa/3KvCu/X20aqn2MSz3A5nfgirtwjP8AqqcdTJd1YdXZomqwqLDz39e5yf4UtLDI8aktYv8AUsNVT+n7uFNZ12TZoUkNoSiybIyx4AJiLq6fXAxGLissSr9wpUiYPT7UXt1fVYxRUmNVZTCkmrcdqK6jrzyxR2xWTZEKqjRI0icsdiNcd7XFen5nKqr/AMMunnmb0ONy0cBr6qQc9hkI2yo7pMSQTF6WPZ5M2BKGicknufdtVTUiJ28BZimD5blejpA5j7ewqsLjMViuaCRWnALM5U6OVUR3KeNCJyr2o1dU4lsrMF23jQylc6GtlHy6xtIoVROUZpkPLKeulkav+PuQ0X+nh5It7SU7HO1aCtxqqKIaa/lYtuG1Mrf8z3L+PHniP+1cR8D488R/2riPgfHniP8AtXEfA+PPEf8AauI+B8eeI/7VxHwPjzxH/auI+B8eeI/7VxHwPjzxH/auI+B8eeI/7VxHwPjzxH/auI+B8eeI/wC1cR8D488R/wBq4j4Hx54j/tXEfA+PPEf9q4j4Hw0km+pLhjXaqCyxqpEJ6f0OWoDVGRv+V6L+PENtngu3EiEIrXTfhkfLq20lhTXmGGbMyy5rohHf19yIif08GZleD5bier44ob6mfV5pFdzq1siVZSDCw2XBAHVXcoIs0itTsRztE46eB5tQ5LK5pCNq45zwMgeOIBsiXKZi91HrMmWvisd7cnufd9UXR6+qRyszuHNspYEkVWL1Aw2GUWwXHSMkqPWvkxRQ67qNIve5ho0YndysE8h2dFTwcXku2yxx7kRkTGZxnZKdjXq9nxHM0FDs+oiPeN7a4dZHOBUYYJVTmVXOVXOcqq5yqqqqquqqqr2qqr6KjmqqKioqKi6Kip2oqKnaiovAIOVSHbnY6xy88XJZxWZPHY5yvf8ADszUM2yc93KwbW2I7MAAN5ACEq8yElYXcq+yiR3SbXF7Zga/KKkDZCRnSZNW2TJHLruoQX+7hlkxWLIEMhBnf0m+pZmDbavhXOeRlKC8vjCBPosMlt1H8ODFM0sS+ymK/V0gRWvgwHtaE7ZB1kxos26vbOfc3Fkd8qwtLSXIn2E6STTnPLmSiFkSCu07XOcq9npMK6obSwpbitO2TX2tVMkV9jBkMRUaeJMikFIjlRFVOZjkXReIWC7kOhU2eyelHo7wIgQKLNJi8o/hxIwmiiUOVTH+1HCNrIM8iuDHbHP3aLJ9RzdrdubJUzAolBl+TQS6LiAit9qgqJI11/Vphr/ujsXSpY7pMVZ6k+H+mQtrtx7JzsyENA4jk04quXMAhYulFcSSOVUy4Am/7aQ9dLYbVG9UntYth6hcaqLHfneUd7q8QjFEslK9whC+J5TJA5qxXhohSh93GdVYecYOoTxxymNPLlnNKlSjFkSZMgrzSJEgz3EMc5iOcQpikcrnOcquc5VVV19NjzIcg8SZEOKVElxSkBJiyQEaUEiOcTmFCcJWI5j2qjmuRFRdeEkWhY7M5xdYlVmEcIO6snEMIvwvJ4wBsSGMN+KKVTiArWAnBOjQgjvjNd6fImz5cavgQo55s+wmmbHg18GIF8iZPmyX+xGhQownFKR3sjG1XL2JxeZeV0gdO1/wfEq+TzsfV4pXHkfCYxALLnDjzZanJNmtERQrPlHcNGscjU9OpMuYsgtMRVpsur4yOeSzxWxMBbQAwJLgDkzYLwCmw2FK0Pf4gFJqxHNUEuDLjT4MsAZcGfCOyTCnwpQmHiToUkSuFJhy45GkERqq0g3I5FVFT09+PwJBI11uTPJjkdwlmxzNxyvZHn5fIjTIzmAVSCPCrZEcqq08S2L2KjV9QioZ8gkm722nDxqS4j5skz8dmjNOxCTJlSOYA0ZHDMrI0cS6Bi1LF0TmT08WMJ1hxMFxekrukkx8iFJssgjNy6Xagj8yiiSi113ChH0RHOWvbzKvKmnqA+LO65Ymd4tdQGhSY4EGNaY5GdlsW1kg5kHKkBqqafDAiormunry6cy+naJ2qvYiJ9/G5OSVpnnq7vO8rsqh5CvMqU8q8nFqBMI9zl6IK1whjTXRrGoiaIiJ6h20yGxkEjVdPneKTrcoivA74KG8hLcicRjmqgZFX1RkTXRw3Ki9ir6dWlIiKMU+GQiLporGSBuci69mitT1HZPGiNG+wmOG1PsRjpBFaifgjV9NERWNKgyMeo3q9GERjkcrHqNzCI1+mi8rkXT7FReJaYtnlBLo1JzQCX8Sxr7ZgnojuhLDXR7OGQkdV5OqwjUNy8/TFzdNvnLB/fvvB+POWD+/feD8ecsH9++8H485YP7994Px5ywf377wfjzlg/v33g/HnLB/fvvB+POWD+/feD8ecsH9++8H485YP7994Px5ywf377wfjzlg/v33g/HnLB/fvvB+POWD+/feD8ecsH9++8H485YP7994Px5ywf377wfjzlg/v33g/HnLB/fvvB+POWD+/feD8ecsH9++8H485YP7994Px5ywf377wfjzlg/v33g/HnLB/fvvB+POWD+/feD8ecsH9++8H485YP7994Px5ywf377wfjzlg/v33g/HnLB/fvvB+POWD+/feD8Q0yrO6CLRITnnvx+JYz7YgmJzd3hisY9bDESQqcnWe96B5ufpF5em4puRg+qR5OmPm5Gc7ldyM53PfyN10TVVXT7VX+3P/9k=';

    public function loadServiceManager(S3ObjectManager $s3, LoginManager $login, $config )
    {
        $this->s3                   = $s3;
        $this->login                = $login;
        $aip_config                 = $config['aip_config'];

        $this->secret               = $config["secret"];
        $this->aip_enabled          = $aip_config['aip_enabled'];
    }

    /**
     * Generates the requests to the AWS Lambda function to create a profile book
     * @param Request $request Request Object
     * @param integer $programmeId id of the programme
     *
     * @return array
     * @throws InvalidResourceException
     *
     * @throws ResourceNotFoundException
     */
    public function generateProfileBook(Request $request, $programmeId)
    {   
        $user = $this->getCurrentUserObj($request);
        $scope = $this->getCurrentUserScope($request);

        /** @var Programme $programme */
        $programme = $this->entityManager
            ->getRepository(Programme::class)
            ->findOneBy(["id"=>$programmeId]);

        $this->checkReadWriteAccessToProgramme($request,$programme);

        $profileBookInfo = [];
        $people = [];
        $people["participants"] = [];

        $programme->setForParticipant(true);
        $programme->setIncludeHidden(true);
        $programme->setRequestorId($user->getId());

        if( $scope == "studysuper" ) {
            $programme->setRequestorScope($scope);
        }

        $serviceToken = "";

        //Get Authorization Header
        $headers = $request->headers;
        $authHeader = $headers->get('Authorization');

        //Check if Header value starts with 'Bearer'
        if($authHeader) {
            // API request. Check access_token in 'users' table
            $oauthAccessToken = trim(substr($authHeader, strlen((string) self::$BEARER_HEADER), strlen($authHeader)));
            $serviceToken = $this->login->generateServiceToken( $oauthAccessToken );
        }

        if( $serviceToken ) {
            $profileBookInfo["service_token"] = $serviceToken->getOauthAccessToken();

            /** @var Programme $programme */
            $programme = $this->entityManager
                ->getRepository(Programme::class)
                ->findOneBy(['id' => $programmeId]);

            if( $programme ) {
                //******** labels section ********//
                //set programme date range label
                $startMonth = "";
                $startYear = "";

                $endMonth = "";
                $endYear = "";

                if( !is_null($programme->getStartDate(true)) ) {
                    $startMonth = $programme->getStartDate(true)->format("F");
                    $startYear = $programme->getStartDate(true)->format("Y");
                }

                if( !is_null($programme->getEndDate(true)) ) {
                    $endMonth = $programme->getEndDate(true)->format("F");
                    $endYear = $programme->getEndDate(true)->format("Y");
                }

                if( strcmp($startMonth,$endMonth) != 0 || strcmp($startYear,$endYear) != 0 ) {
                    if( strcmp($startYear,$endYear) != 0 ) {
                        //diff month; diff year
                        $programmeDateLabel = $startMonth . " " . $startYear. " - " . $endMonth . " " . $endYear;
                    } else {
                        //diff month; same year
                        $programmeDateLabel = $startMonth . " - " . $endMonth . " " . $startYear;
                    }
                } else {
                    //same month and year
                    $programmeDateLabel = $startMonth . " " . $startYear;
                }

                //******** people section ********//
                $courses = $programme->getPublishedCourses();

                $participants = [];
                /** @var Course $course */
                foreach( $courses as $course ) {
                    /** @var User $studentObject */
                    foreach($course->getStudents(true) as $studentObject ) {

                        /** @var UserProfileCache $cacheProfile */
                        $cacheProfile =  $studentObject->getCacheProfile();
                        if (!$cacheProfile) continue;

                        $preferredEmail = match ($cacheProfile->getPreferredEmail()) {
                            0 => $cacheProfile->getPersonalEmail(),
                            1 => $cacheProfile->getWorkEmail(),
                            default => $cacheProfile->getUpnEmail(),
                        };

                        $preferredPhone = match ($cacheProfile->getPreferredPhone()) {
                            0 => $cacheProfile->getPersonalPhonePrefix().$cacheProfile->getPersonalPhone(),
                            1 => $cacheProfile->getWorkPhonePrefix().$cacheProfile->getWorkPhone(),
                            2 => $cacheProfile->getCellPhonePrefix().$cacheProfile->getCellPhone(),
                            default => "",
                        };

                        $participants[ $studentObject->getPeoplesoftId() ] = [
                            "peoplesoft_id" => $cacheProfile->getUser()->getPeoplesoftId(),
                            "bio"           => $cacheProfile->getBio(),
                            "nationality"   => $cacheProfile->getNationality(),
                            "position"      => $cacheProfile->getJobTitle(),
                            "company"       => $cacheProfile->getOrganizationTitle(),
                            "state"         => $cacheProfile->getState(),
                            "country"       => $cacheProfile->getCountry(),
                            "phone"         => $preferredEmail,
                            "phone"         => trim($preferredPhone)
                        ];
                    }
                }

                foreach( $participants as $person ) {
                    $profileToAdd["peoplesoft_id"] = $person['peoplesoft_id'];
                    try {
                        $encrypted_profile = $this->getProfileForProfileBook($person['peoplesoft_id']);
                    } catch (\Exception) {
                        $encrypted_profile = false;
                    }

                    try {
                        $encrypted_avatar = $this->getAvatar($person['peoplesoft_id']);
                    } catch (\Exception) {
                        $encrypted_avatar = false;
                    }

                    if ($encrypted_avatar && $encrypted_avatar['avatar']) {
                        $profileToAdd["img"] = $encrypted_avatar['avatar'];
                    } else {
                        $profileToAdd["img"] = $this->encryptAvatar(self::$DEFAULT_AVATAR, $person['peoplesoft_id']);
                    }

                    if ($encrypted_profile && $encrypted_profile['profile']) {
                        $profileToAdd["profile"] = $encrypted_profile['profile'];
                    }

                    array_push($people["participants"],$profileToAdd);
                }

                $profileBookInfo["people"] = $people["participants"];

                //******** consolidate all data ********//
                $profileBookInfo["title"]             = $programme->getName();
                $profileBookInfo["date"]              = $programmeDateLabel;
                $profileBookInfo["companyLogoStatus"] = $programme->getCompanyLogo();
                $profileBookInfo["role"]              = "Participants";

                $bookPrefix = substr( $this->cleanName($programme->getName()), 0, 150);
                if( $programme->getStartDate() ) {
                    $bookPrefix = $bookPrefix . "-" . $programme->getStartDate()->format("MY");
                }
                $profileBookInfo["book_prefix"] = $bookPrefix;
                unset($profileBookInfo['service_token']);
                $profileBookInfo = [$profileBookInfo];

                $programmeName = $this->cleanName($programme->getName());
                $this->s3->setCustomMetadata([
                    "filename" => $programmeName,
                ]);

                $resultFull = $this->s3->uploadToS3(
                    "preprocessed-resources/data-profile-book-full/" . $programme->getId() . ".json",
                    json_encode($profileBookInfo, JSON_UNESCAPED_UNICODE),
                    true
                );

                $resultBusiness = $this->s3->uploadToS3(
                    "preprocessed-resources/data-profile-book-business/" . $programme->getId() . ".json",
                    json_encode($profileBookInfo, JSON_UNESCAPED_UNICODE),
                    true
                );

                $this->log( "Request profile book generation Full: " . json_encode($resultFull) . " Business: " . json_encode($resultBusiness) );

                /** @var Course $course */
                foreach( $courses as $course ) {
                    $this->log("Need to reset backup for course " . $course->getId());

                    $backupService = $this->backup;
                    $backupService->updateCoursebackup($course);
                }

                return [$resultFull, $resultBusiness];

            } else {
                $this->logger->error('Invalid Programme');
                throw new ResourceNotFoundException('Programme not found');
            }
        } else {
            $this->logger->error('Unable to create ServiceToken for Profile Book');
            throw new ResourceNotFoundException('Unable to create ServiceToken for Profile Book');
        }
    }

    /**
     * check if a profile book is available for the programme
     * checks if user's Token is valid
     * @param Request $request Request Object
     * @param integer $programmeId id of the programme
     *
     * @return array
     * @throws InvalidResourceException
     *
     * @throws ResourceNotFoundException
     */
    public function getProfileBook(Request $request, $programmeId)
    {

        $user = $this->getCurrentUserObj($request);

        /** @var Programme $programme */
        $programme = $this->entityManager
            ->getRepository(Programme::class)
            ->findOneBy(['id' => $programmeId]);

        if( $programme ) {


            $programme->setForParticipant(true);
            $programme->setForStaff(false);
            $programme->setRequestorId($user->getId());

            $this->checkReadWriteAccessToProgramme($request,$programme);

            $this->log("Generating temporary Profile Book URLs for " . $user->getPeoplesoftId());

            $bookPrefix = substr( $this->cleanName($programme->getName()), 0, 150);
            if( $programme->getStartDate() ) {
                $bookPrefix = $bookPrefix . "-" . $programme->getStartDate()->format("MY");
            }


            return ["profile-books" => ["id"                        => $programme->getId(), "programme"                 => $programme->getId(), "book_prefix"               => $bookPrefix, "book_timestamp_full"       => $programme->getBookTimestampFull(), "book_timestamp_business"   => $programme->getBookTimestampBusiness(), "last_person_update"        => $programme->getLatestUpdatedPersonTimestamp(), "full"                      => $this->s3->generateProfileBookTempUrl( $programmeId, "full", $user->getPeoplesoftId() ), "business"                  => $this->s3->generateProfileBookTempUrl( $programmeId, "business", $user->getPeoplesoftId() )]];

        } else {
            $this->logger->error('Invalid Programme');
            throw new ResourceNotFoundException('Programme not found');
        }
    }


    /**
     * checks if user's Token is valid
     * check if program is accessible by user
     * create a s3 bucket object in location using token and progid
     * @param Request $request Request Object
     * @param integer $programmeId id of the programme
     *
     * @return array
     *
     * @throws PermissionDeniedException
     * @throws ResourceNotFoundException
     */
    public function deleteProfileBooks(Request $request, $programmeId)
    {
        $scope = $this->getCurrentUserScope($request);
        $user = $this->getCurrentUserObj($request);

        if($scope!='studysuper'){
            throw new PermissionDeniedException('Permission Denied for the current user ');
        }

        //get Auth Header
        $authHeader = $request->headers->get('Authorization');

        // Find the Programme
        $programme = $this->entityManager
            ->getRepository(Programme::class)
            ->findOneBy(['id' => $programmeId]);


        $this->log( "scope :".json_encode($scope) );

        //check if user has access to the programme
        $programme->setRequestorId($user->getId());
        $programme->setRequestorScope($scope);

        //submit a profile refresh for profile-book by uploading a json file
        /** @var UserToken $serviceToken */
        $serviceToken = $this->login->generateServiceToken( $authHeader );
        if( $serviceToken ) {
            $this->log("Triggering a generation for profile book cleanup under programme " . $programmeId);
            $programmeData = ["programme_id" => $programmeId, "service_token" => $serviceToken->getOauthAccessToken()];

            $result = $this->s3->uploadToS3(
                "cleanup/programmes/" . $programmeId . ".json",
                json_encode($programmeData),
                true
            );

            $this->log( "profilebook cleanup program json created for  [" . $programmeId . "]:" . json_encode($result) );

            return ["status"=>"success"];
        }
        else{
            return ["status"=>"permission denied"];
        }


    }

    /**
     * Handler that provides an encrypted profile information for the AWS Lambda Function
     *  checks if user's Token is valid
     * @param Request $request Request Object
     * @param String $peoplesoftId peoplesoft id of the user
     *
     * @return array
     */
    public function getPersonInfo(Request $request, $peoplesoftId)
    {
        return $this->getProfileForProfileBook($peoplesoftId);
    }

    private function getProfileForProfileBook($peoplesoftId)
    {
        $name = "";
        $profile["first_name"] = "";
        $profile["last_name"] = "";
        $profile["bio"] = "";
        $nationality = [];
        $profile["main_job"]["job_title"] = "";
        $profile["main_job"]["organisation"] = "";
        $profile["main_job"]["city"] = "";
        $profile["main_job"]["country"] = "";
        $profile["main_job"]["state"] = "";
        $email = "";
        $phone = "";

        /** @var User $user */
        $user   = $this->entityManager
            ->getRepository(User::class)
            ->findOneBy(['peoplesoft_id' => $peoplesoftId]);

        $studyProfile = null;
        if ($user){
            if ($user->getCoreProfile()){
                /** @var UserProfile $studyProfile */
                $studyProfile = $user->getCoreProfile();
            } else {
                if ($user->getCacheProfile()){
                    /** @var UserProfileCache $studyProfile */
                    $studyProfile = $user->getCacheProfile();
                }
            }
        }

        if ($studyProfile){
            $name = trim(($studyProfile->getFirstname() ?: "")." ".strtoupper(($studyProfile->getLastname() ?: "")));
            $profile["first_name"] = ($studyProfile->getFirstname() ?: "");
            $profile["last_name"] = ($studyProfile->getLastname() ?: "");
            $profile["bio"] = ($studyProfile->getBio() ?: "");
            $nationality = ($studyProfile->getNationality() ? explode(",",$studyProfile->getNationality()) : []);
            $profile["main_job"]["job_title"] = ($studyProfile instanceof UserProfile ? ($studyProfile->getPreferredJobTitle() ?: "") : ($studyProfile->getJobTitle() ?: ""));
            $profile["main_job"]["organisation"] = ($studyProfile->getOrganizationTitle() ?: "");
            $profile["main_job"]["city"] = ($studyProfile->getCity() ?: "");


            if ($studyProfile->getCountryCode()) {
                /** @var Country $country */
                $country = $this->entityManager
                    ->getRepository(Country::class)
                    ->findOneBy( ['ps_country_code' => $studyProfile->getCountryCode()]);

                if ($country) {
                    $profile["main_job"]["country"] = ($country->getTitle() ?: "");
                    if ($country->getStates()) {
                        /** @var States $state */
                        foreach ($country->getStates() as $state) {
                            if ($studyProfile->getState() === $state->getStateCode()) {
                                $profile["main_job"]["state"] = $state->getStateName();
                                break;
                            }
                        }
                    }
                }
            }

            $prefEmail = $studyProfile->getPreferredEmail();
            $hideEmail = false;
            if (method_exists($studyProfile, 'getHideEmail')){
                $hideEmail = $studyProfile->getHideEmail();
            }

            if (isset($prefEmail) && !$hideEmail){
                $email = match ($prefEmail) {
                    0 => $studyProfile->getPersonalEmail(),
                    1 => $studyProfile->getWorkEmail(),
                    default => '',
                };
            }

            $prefPhone = $studyProfile->getPreferredPhone();
            $hidePhone = false;
            if (method_exists($studyProfile, 'getHidePhone')){
                $hidePhone = $studyProfile->getHidePhone();
            }

            if (isset($prefPhone) && !$hidePhone){
                $phone = match ($prefPhone) {
                    0 => trim(($studyProfile->getPersonalPhonePrefix() ? "+" . $studyProfile->getPersonalPhonePrefix() : "") . " " . $studyProfile->getPersonalPhone()),
                    1 => trim(($studyProfile->getWorkPhonePrefix() ? "+" . $studyProfile->getWorkPhonePrefix() : "") . " " . $studyProfile->getWorkPhone()),
                    2 => trim(($studyProfile->getCellPhonePrefix() ? "+" . $studyProfile->getCellPhonePrefix() : "") . " " . $studyProfile->getCellPhone()),
                    default => '',
                };
                
            }

        }

        $personInfo = [
            "name" => $name,
            "firstname" => $profile["first_name"],
            "lastname" => $profile["last_name"],
            "bio" => $profile["bio"],
            "nationality" => implode(", ", $nationality),
            "position" => $profile["main_job"]["job_title"],
            "company" => $profile["main_job"]["organisation"],
            "city" => $profile["main_job"]["city"],
            "country" => $profile["main_job"]["country"],
            "state" => $profile["main_job"]["state"]
        ];

        $email = trim($email);
        if (strlen($email) > 0) {
            if (!$hideEmail) {
                $personInfo["email"] = $email;
            }
        }

        $phone = trim($phone);
        if (strlen($phone) > 0) {
            if (!$hidePhone) {
                $personInfo["phone"] = $phone;
            }
        }

        $now = new \DateTime();

        $encryptedProfile = $this->encrypt(
            $this->secret . $peoplesoftId, //key
            $now->format("YmdHis")."00", //iv
            json_encode($personInfo) //data
        );

        return ["peoplesoft_id" => $peoplesoftId, "profile" => $encryptedProfile];
    }

    /**
     * Handler that provides an encrypted profile avatar information for the AWS Lambda Function
     *  checks if user's Token is valid
     * @param Request       $request            Request Object
     * @param integer       $peoplesoftId       peoplesoft id of the user
     *
     * @throws ResourceNotFoundException
     *
     * @return array
     */
    public function getAvatarInfo(Request $request, $peoplesoftId)
    {
        return $this->getAvatar($peoplesoftId);
    }

    /**
     * Handler to Fetch User avatar from CDN
     *
     * @param $peoplesoftId
     *
     * @return array
     * @throws ResourceNotFoundException
     */
    private function getAvatar($peoplesoftId)
    {
        $path = "myinsead/profile-images/" . md5((string) $peoplesoftId) . ".jpg";

        if( !$this->s3->checkIfCdnItemExists($path) ) {
            $this->log('User Picture not found ('.$peoplesoftId.')');
            throw new ResourceNotFoundException('User Picture not found');
        }

        $obj = $this->s3->getCdnItem($path);

        $avatar = base64_encode((string) $obj['Body']);

        return ["peoplesoft_id" => $peoplesoftId, "avatar" => $this->encryptAvatar($avatar, $peoplesoftId)];
    }

    private function encryptAvatar($base64Image, $peoplesoftId) {
        $now = new \DateTime();

        return $this->encrypt(
            $this->secret . $peoplesoftId, //key
            $now->format("YmdHis")."00", //iv
            $base64Image //data
        );
    }

    /**
     * Handler that checks S3 and updates the profile book timestamps
     *  checks if user's Token is valid
     * @param Request $request Request Object
     * @param integer $programmeId Id of the Programme to update
     *
     * @return array
     * @throws ResourceNotFoundException
     * @throws ORMException
     * @throws OptimisticLockException
     */
    public function setProfileBookTimestamp(Request $request, $programmeId)
    {

        /** @var Programme $programme */
        $programme = $this->entityManager
            ->getRepository(Programme::class)
            ->findOneBy(['id' => $programmeId]);

        if( $programme ) {

            $this->log("Generating temporary Profile Book URLs for " . $programmeId);

            $modificationDate = $this->s3->getObjectLastUpdatedDate($programmeId,"full");
            if( $modificationDate && $modificationDate > $programme->getBookTimestampFull() ) {
                $programme->setBookTimestampFull($modificationDate);
            }

            $modificationDate = $this->s3->getObjectLastUpdatedDate($programmeId,"business");
            if( $modificationDate && $modificationDate > $programme->getBookTimestampBusiness() ) {
                $programme->setBookTimestampBusiness($modificationDate);
            }

            $em = $this->entityManager;
            $em->persist($programme);
            $em->flush();

            return ["programmes" => $programme];

        } else {
            $this->logger->error('Invalid Programme');
            throw new ResourceNotFoundException('Programme not found');
        }
    }

    /**
     * Handler that checks the user's Programmes
     *  checks if user's Token is valid
     * @param Request       $request            Request Object
     * @param integer       $peoplesoftId       peoplesoft id of the user
     *
     * @return array
     */
    public function getPersonProgrammes(Request $request, $peoplesoftId)
    {

        $programmes = [];

        /** @var User $user */
        $user = $this->entityManager
            ->getRepository(User::class)
            ->findOneBy(["peoplesoft_id"=>$peoplesoftId]);

        /** @var Programme $items */
        $items = $this->entityManager
            ->getRepository(Programme::class)
            ->findAll();

        /** @var Programme $programme */
        foreach( $items as $programme ) {
            $programme->setRequestorId($user->getId());
            $programme->setForParticipant(true);
            $programme->setForStaff(false);

            $toInclude = $programme->checkIfMy() && ( $programme->checkIfLive() || $programme->checkIfPending() );

            if( $toInclude ) {
                array_push($programmes, $programme);
            }
        }

        return ['programmes' => $programmes];
    }

    /**
     * Handler that gets the list of programmes with outdated profile books
     *  checks if user's Token is valid
     * @param Request       $request            Request Object
     *
     * @throws ResourceNotFoundException
     *
     * @return array
     */
    public function getOutdatedProfileBooks(Request $request)
    {

        $pendingProgrammes = [];
        $liveProgrammes = [];
        $completedProgrammes = [];

        $user = $this->getCurrentUserObj($request);

        /** @var Programme $items */
        $items = $this->entityManager
            ->getRepository(Programme::class)
            ->findAll();

        /** @var Programme $programme */
        foreach( $items as $programme ) {
            $programme->setForParticipant(true);
            $programme->setForStaff(false);
            $programme->setRequestorId($user->getId());

            $toInclude = ($programme->getBookTimestampBusiness() == "" || $programme->getBookTimestampFull() == "");

            //if it is not yet included, check business vs latest person update
            if( !$toInclude && $programme->getLatestUpdatedPersonTimestamp() != "" ) {
                if( $programme->getBookTimestampBusiness() != "" ) {
                    $toInclude = $programme->getLatestUpdatedPersonTimestamp() > $programme->getBookTimestampBusiness();
                }
            }

            //if it is not yet included, check full vs latest person update
            if( !$toInclude && $programme->getLatestUpdatedPersonTimestamp() != "" ) {
                if( $programme->getBookTimestampFull() != "" ) {
                    $toInclude = $programme->getLatestUpdatedPersonTimestamp() > $programme->getBookTimestampFull();
                }
            }

            $programmeObj = ["id" => $programme->getId(), "name" => $programme->getName(), "last_person_update" => $programme->getLatestUpdatedPersonTimestamp(), "book_timestamp_business" => $programme->getBookTimestampBusiness(), "book_timestamp_full" => $programme->getBookTimestampFull()];

            if( $toInclude ) {
                if( $programme->checkIfPending() ) {
                    array_push($pendingProgrammes, $programmeObj);

                } else if( $programme->checkIfLive() ) {
                    array_push($liveProgrammes, $programmeObj);

                } else if( $programme->checkIfCompleted() ) {
                    array_push($completedProgrammes, $programmeObj);

                } else {
                    //in case there are items that are not marked upcoming/live/completed, set them as completed
                    array_push($completedProgrammes, $programmeObj);
                }
            }
        }

        return ['programmes' => ['pending' => $pendingProgrammes, 'live' => $liveProgrammes, 'completed' => $completedProgrammes]];
    }




    /**
     * Encrypt data using AES Cipher (CBC) with 128 bit key
     *
     * reference: https://github.com/chaudhuri-ab/CrossPlatformCiphers/blob/master/PHP_CIPHER/PHP_CIPHER/index.php
     *
     * @param String $key - key to use should be 16 bytes long (128 bits)
     * @param String $iv - initialization vector
     * @param String $data - data to encrypt
     * @return String encrypted data in base64 encoding with iv attached at end after a :
     */
    protected function encrypt($key, $iv, $data) {
        if (strlen($key) < self::$CIPHER_KEY_LEN) {
            $key = str_pad("$key", self::$CIPHER_KEY_LEN, "0"); //0 pad to len 16
        } else if (strlen($key) > self::$CIPHER_KEY_LEN) {
            $key = substr($key, 0, self::$CIPHER_KEY_LEN); //truncate to 16 bytes
        }

        $encodedEncryptedData = base64_encode(openssl_encrypt($data, self::$OPENSSL_CIPHER_NAME, $key, OPENSSL_RAW_DATA, $iv));
        $encodedIV = base64_encode($iv);
        $encryptedPayload = $encodedEncryptedData.":".$encodedIV;

        return $encryptedPayload;

    }
    /**
     * Decrypt data using AES Cipher (CBC) with 128 bit key
     *
     * reference: https://github.com/chaudhuri-ab/CrossPlatformCiphers/blob/master/PHP_CIPHER/PHP_CIPHER/index.php
     *
     * @param String $key - key to use should be 16 bytes long (128 bits)
     * @param String $data - data to be decrypted in base64 encoding with iv attached at the end after a :
     * @return String decrypted data
     */
    protected function decrypt($key, $data) {
        if (strlen($key) < self::$CIPHER_KEY_LEN) {
            $key = str_pad("$key", self::$CIPHER_KEY_LEN, "0"); //0 pad to len 16
        } else if (strlen($key) > self::$CIPHER_KEY_LEN) {
            $key = substr($key, 0, self::$CIPHER_KEY_LEN); //truncate to 16 bytes
        }

        $parts = explode(':', $data); //Separate Encrypted data from iv.
        $decryptedData = openssl_decrypt(base64_decode($parts[0]), self::$OPENSSL_CIPHER_NAME, $key, OPENSSL_RAW_DATA, base64_decode($parts[1]));

        return $decryptedData;
    }
}
